version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install setuptools --upgrade
            python3 setup.py develop
      - save_cache:
          key: deps-{{ checksum "setup.py" }}
          paths:
            - venv
      - run: python3 setup.py flake8
      - run: python3 setup.py test
